"""Alembic script mako template — do not modify."""
"""add users and products tables

Revision ID: 89adea4ed12c
Revises: 
Create Date: 2026-08-21 20:38:41.666475
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '89adea4ed12c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Product name e.g. 'Dell Inspiron 15 3000'"),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Product category for search filtering'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Price in INR (Indian Rupees)'),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Original price before discount'),
    sa.Column('stock_quantity', sa.Integer(), nullable=False, comment='Current stock count'),
    sa.Column('is_available', sa.Boolean(), nullable=False, comment='False when out of stock or delisted'),
    sa.Column('description', sa.Text(), nullable=True, comment='Full product description'),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Flexible product attributes stored as JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index('ix_products_category_price', 'products', ['category', 'price'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the user'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address — used for login"),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's display name"),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt hash of password — NEVER store plain text'),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False, comment='True for demo/seed users'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index('ix_products_category_price', table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
